apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
spec:
  selector:
    matchLabels:
      app: poi
  replicas: 2
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
        - name: poi
          image: "<yourACRName>.azurecr.io/poi:1"
          env:
          - name: SQL_SERVER
            valueFrom:
              secretKeyRef:
                name: sqlsecrets
                key: sqlserver
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: sqlsecrets
                key: sqluser
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sqlsecrets
                key: sqlpw
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: poi-service
spec:
  selector:
    app: poi
  ports:
  - protocol: TCP
    port: 8080
    targetPort: http
  type: LoadBalancer
