apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer
spec:
  selector:
    matchLabels:
      app: tripviewer
  replicas: 2
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
        - name: tripviewer
          image: "<yourACRname>.azurecr.io/tripviewer:1"
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: tripviewer-service
spec:
  selector:
    app: tripviewer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: http
  type: LoadBalancer
