apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips
spec:
  selector:
    matchLabels:
      app: trips
  replicas: 2
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
        - name: trips
          image: "acrtripinsightfun.azurecr.io/trips:1"
          env:
          - name: SQL_SERVER
            valueFrom:
              secretKeyRef:
                name: sqlsecrets
                key: sqlserver
          - name: SQL_USER
            valueFrom:
              secretKeyRef:
                name: sqlsecrets
                key: sqluser
          - name: SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sqlsecrets
                key: sqlpw
          ports:
            - name: http
              containerPort: 80
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: trips-service
spec:
  selector:
    app: trips
  ports:
  - protocol: TCP
    port: 8080
    targetPort: http
  type: LoadBalancer
